/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blobseer_ObjectHandler */

#ifndef _Included_blobseer_ObjectHandler
#define _Included_blobseer_ObjectHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blobseer_ObjectHandler
 * Method:    blob_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_blobseer_ObjectHandler_blob_1init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    blob_free
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_blob_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    blob_create
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_blob_1create
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    get_latest
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_get_1latest
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    read
 * Signature: (JJJ[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_read
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jint);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    append
 * Signature: (JJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_append
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    write
 * Signature: (JJJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_write
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    get_objcount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blobseer_ObjectHandler_get_1objcount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    get_size
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blobseer_ObjectHandler_get_1size
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    get_version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blobseer_ObjectHandler_get_1version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    get_page_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blobseer_ObjectHandler_get_1page_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    get_id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blobseer_ObjectHandler_get_1id
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
