/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blobseer_ObjectHandler */

#ifndef _Included_blobseer_ObjectHandler
#define _Included_blobseer_ObjectHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blobseer_ObjectHandler
 * Method:    blob_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_blobseer_ObjectHandler_blob_1init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     blobseer_ObjectHandler
 * Method:    blob_free
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_blobseer_ObjectHandler_blob_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
